apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website-api
  # namespace: personal-website-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-website-api
  template:
    metadata:
      labels:
        app: personal-website-api
    spec:
      containers:
      - name: personal-website-api
        image: kevinlutzer/personal-website-api:python4
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
