apiVersion: v1
kind: Service
metadata:
  name: personal-website-api
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  namespace: personal-website-api
  labels:
    app: personal-website-api
spec:
  type: LoadBalancer
  selector:
    app: personal-website-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  sessionAffinity: None